name: diskominfotik_bengkalis
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  nb_utils: 3.2.9
  cached_network_image: ^2.3.1
  flutter_statusbarcolor: 0.2.3
  flutter_svg: ^0.19.0
  http: ^0.12.2
  flutter_html: ^1.1.1
  url_launcher: ^5.7.10
  link_text: ^0.1.3
  indonesia: ^1.0.1
  share: ^0.6.5+4
  flutter_cached_pdfview: ^0.3.1
  youtube_player_flutter: ^7.0.0+7
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.1+7
  clippy_flutter: 1.1.1
  carousel_slider:
  flutter_signin_button: ^1.1.0
  get: 3.15.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner: ^1.9.0
    #flutter packages pub run build_runner build

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - images/dashboard/
    - images/icons/

  fonts:
    - family: Regular
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf

    - family: Medium
      fonts:
        - asset: fonts/SF-Pro-Display-Medium.otf

    - family: Semibold
      fonts:
        - asset: fonts/SF-Pro-Display-Semibold.otf

    - family: Bold
      fonts:
        - asset: fonts/SF-Pro-Display-Bold.otf
    - family: product-sans
      fonts:
        - asset: fonts/product-sans/Product-Sans-Regular.ttf
    - family: source-sans-pro
      fonts:
        - asset: fonts/source-sans-pro/SourceSansPro-Regular.ttf
    - family: intro
      fonts:
        - asset: fonts/intro/Intro.otf
    - family: roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
    - family: lato
      fonts:
        - asset: fonts/lato/Lato-Regular.ttf